print('-' *35)
print('Tugas 1 SISOP Kelas A')
print('-' *35)
print('Nama : Awal Lidya Musaffak')
print('NPM  : 21083010088')
print('-' *35)
print('notes:')
print('-' *35)
print('Halo dunia!')
print('Ini adlah skrip Bash pertamaku di Linux')
